[package]
name = "rsnake"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.28.1"
#see https://docs.rs/ratatui/latest/ratatui/widgets/trait.WidgetRef.html need to have better performance avoiding cloning widget each time
ratatui = { version = "0.29", features = ["unstable-widget-ref"] }
rand = "0.9.0"
