[package]
name = "rsnake"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.28.1"
#To have enum toString and get their name
strum = "0.26.3"
strum_macros = "0.26.4"
