
# Snake Game Configuration
# ---------------------------
# classic_mode:     true for classic rules (walls kill, no wrapping)
# uncaps_fps:       disables frame limiting (true = no limit) 
# life:             starting lives
# nb_of_fruit:      number of fruits available in the game at once
# body_symbol:      character for the snake's body  
# head_symbol:      character for the snake's head
# snake_length:     initial length of the snake
# speed:            speed of the snake (Slow, Normal, Fast, Tremendous)
# save/load:        save/load game parameters to/from file, not very useful from a file, but useful from the CLI

speed = "Normal"
head_symbol = "🎄"
body_symbol = "❄️"
snake_length = 10
life = 3
nb_of_fruit = 5
uncaps_fps = false
classic_mode = false
save = false
load = false
